services:
  caddy:
    image: caddy:latest
    environment:
      - TS_UPDATE=1
      - TIME_ZONE=Europe/Berlin
    volumes:
      - /mnt/shared/caddy/etc:/etc/caddy
      - /mnt/shared/caddy/domains:/etc/caddy/domains
      - /mnt/shared/caddy/site:/srv
      - /mnt/shared/caddy/caddy_data:/data
      - /mnt/shared/caddy/caddy_config:/config
    networks:
      - caddy_network
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1

networks:
  caddy_network:
    driver: overlay
    attachable: true
