services:
  filebrowser:
    image: filebrowser/filebrowser
    environment:
      FB_CONFIG: "/config/filebrowser.json"
      FB_DATABASE: "/config/database.db"
    ports:
      - "49289:80"
    volumes:
      - /mnt/shared/ftp/config:/config
      - /mnt/shared/ftp/data:/srv
    networks:
      - ftp_network
    deploy:
      placement:
        constraints: [node.role == worker]

  ftpserver:
    image: nginx:alpine
    ports:
      - "49288:80"
    volumes:
      - /mnt/shared/ftp/config:/etc/nginx/conf.d
      - /mnt/shared/ftp/data:/usr/share/nginx/html
    networks:
      - ftp_network
    deploy:
      placement:
        constraints: [node.role == worker]

networks:
  ftp_network:
    driver: overlay
    attachable: true

