services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    volumes:
      - /mnt/shared/heimdall/config:/config
    networks:
      - heimdall_network
    ports:
      - 51908:80
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
      update_config:
        order: start-first

networks:
  heimdall_network:
    driver: overlay
    attachable: true

