services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    volumes:
      - heimdall_config_shared:/config
    networks:
      - heimdall_network
    ports:
      - 51908:80
    deploy:
      replicas: 1

networks:
  heimdall_network:
    driver: overlay
    attachable: true

volumes:
  heimdall_config_shared:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.9,rw"
      device: ":/volume1/Shared/docker/heimdall/config"
