services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /mnt/shared/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: H3H*sW7GXv7Eiz
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: overlay
    attachable: true

