services:
  mongodb:
    image: mongo:8.0.6
    ports:
      - "27017:27017"
    volumes:
      - /mnt/shared/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: H3H*sW7GXv7Eiz
    networks:
      - mongo_network
    deploy:
      update_config:
        order: start-first
      placement:
        constraints: [node.role == manager]

networks:
  mongo_network:
    driver: overlay
    attachable: true

