services:
  ntfy:
    image: binwiederhier/ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Berlin
    user: "1000"
    volumes:
      - /mnt/shared/ntfy/cache:/var/cache/ntfy
      - /mnt/shared/ntfy/etc:/etc/ntfy
    networks:
      - ntfy_network
    ports:
      - 35978:80
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://127.0.0.1:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    deploy:
      update_config:
        order: start-first
      placement:
        constraints: [node.role == worker]

networks:
  ntfy_network:
    driver: overlay
    attachable: true

