services:
  ntfy:
    image: binwiederhier/ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Berlin
    user: "1000"
    volumes:
      - ntfy_cache_shared:/var/cache/ntfy
      - ntfy_etc_shared:/etc/ntfy
    networks:
      - ntfy_network
    ports:
      - 35978:80
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://127.0.0.1:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s

networks:
  ntfy_network:
    driver: overlay
    attachable: true

volumes:
  ntfy_cache_shared:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.9,rw"
      device: ":/volume1/Shared/docker/ntfy/cache"
  ntfy_etc_shared:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.9,rw"
      device: ":/volume1/Shared/docker/ntfy/etc"
