services:
  pihole:
    image: pihole/pihole:latest
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /mnt/shared/pihole/etc:/etc/pihole
      - /mnt/shared/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - host

networks:
  host:
    external: true
    name: host

