services:
  pihole:
    image: pihole/pihole:latest
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /mnt/shared/pihole/etc:/etc/pihole
      - /mnt/shared/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      - pihole_network
    ports:
      - "0.0.0.0:53:53/tcp"
      - "0.0.0.0:53:53/udp"
      - "0.0.0.0:8080:80/tcp"
    deploy:
      replicas: 1

networks:
  pihole_network:
    driver: overlay
    attachable: true

