services:
  teamspeak:
    image: ertagh/teamspeak3-server:latest-box
    environment:
      - TS_UPDATE=1
      - TIME_ZONE=Europe/Berlin
    volumes:
      - /mnt/shared/teamspeak/data:/teamspeak/save/
    networks:
      - teamspeak_network
    ports:
      - 10011:10011/tcp
      - 30033:30033/tcp
      - 9987:9987/udp
    deploy:
      replicas: 1

networks:
  teamspeak_network:
    driver: overlay
    attachable: true

