services:
  uptimekuma:
    image: louislam/uptime-kuma
    volumes:
      - /mnt/shared/uptimekuma/data:/app/data
    networks:
      - uptimekuma_network
    ports:
      - 3001:3001
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M

networks:
  uptimekuma_network:
    driver: overlay
    attachable: true

