services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_SCHEDULE="0 0 1 * * *" 
      - TZ=Europe/Berlin 
      - WATCHTOWER_CLEANUP="true" 
      - WATCHTOWER_DEBUG="false"     
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

